// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package io.ltbl.ldknodern

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the detils of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.ptr.ByReference
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.util.concurrent.atomic.AtomicBoolean
import java.util.concurrent.atomic.AtomicLong

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    @JvmField var capacity: Int = 0
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : RustBuffer(), Structure.ByValue
    class ByReference : RustBuffer(), Structure.ByReference

    companion object {
        internal fun alloc(size: Int = 0) = rustCall() { status ->
            _UniFFILib.INSTANCE.ffi_ldk_node_2e4a_rustbuffer_alloc(size, status).also {
                if(it.data == null) {
                    throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
                }
            }
        }

        internal fun free(buf: RustBuffer.ByValue) = rustCall() { status ->
            _UniFFILib.INSTANCE.ffi_ldk_node_2e4a_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

/**
 * The equivalent of the `*mut RustBuffer` type.
 * Required for callbacks taking in an out pointer.
 *
 * Size is the sum of all values in the struct.
 */
class RustBufferByReference : ByReference(16) {
    /**
     * Set the pointed-to `RustBuffer` to the given value.
     */
    fun setValue(value: RustBuffer.ByValue) {
        // NOTE: The offsets are as they are in the C-like struct.
        val pointer = getPointer()
        pointer.setInt(0, value.capacity)
        pointer.setInt(4, value.len)
        pointer.setPointer(8, value.data)
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
// The FfiConverter interface handles converter types to and from the FFI
//
// All implementing objects should be public to support external types.  When a
// type is external we need to import it's FfiConverter.
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): Int

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity.toLong()).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
            val item = read(byteBuf)
            if (byteBuf.hasRemaining()) {
                throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
            }
            return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

// FfiConverter that uses `RustBuffer` as the FfiType
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.
// Error runtime.
@Structure.FieldOrder("code", "error_buf")
internal open class RustCallStatus : Structure() {
    @JvmField var code: Int = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    fun isSuccess(): Boolean {
        return code == 0
    }

    fun isError(): Boolean {
        return code == 1
    }

    fun isPanic(): Boolean {
        return code == 2
    }
}

class InternalException(message: String) : Exception(message)

// Each top-level error class has a companion object that can lift the error from the call status's rust buffer
interface CallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: Exception> rustCallWithError(errorHandler: CallStatusErrorHandler<E>, callback: (RustCallStatus) -> U): U {
    var status = RustCallStatus();
    val return_value = callback(status)
    if (status.isSuccess()) {
        return return_value
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

// CallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
object NullCallStatusErrorHandler: CallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> rustCall(callback: (RustCallStatus) -> U): U {
    return rustCallWithError(NullCallStatusErrorHandler, callback);
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "ldk_node"
}

private inline fun <reified Lib : Library> loadIndirect(
    componentName: String
): Lib {
    return Native.load<Lib>(findLibraryName(componentName), Lib::class.java)
}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

internal interface _UniFFILib : Library {
    companion object {
        internal val INSTANCE: _UniFFILib by lazy {
            loadIndirect<_UniFFILib>(componentName = "ldk_node")

        }
    }

    fun ffi_ldk_node_2e4a_Builder_object_free(`ptr`: Pointer,
                                              _uniffi_out_err: RustCallStatus
    ): Unit

    fun ldk_node_2e4a_Builder_new(
        _uniffi_out_err: RustCallStatus
    ): Pointer

    fun ldk_node_2e4a_Builder_from_config(`config`: RustBuffer.ByValue,
                                          _uniffi_out_err: RustCallStatus
    ): Pointer

    fun ldk_node_2e4a_Builder_build(`ptr`: Pointer,
                                    _uniffi_out_err: RustCallStatus
    ): Pointer

    fun ffi_ldk_node_2e4a_Node_object_free(`ptr`: Pointer,
                                           _uniffi_out_err: RustCallStatus
    ): Unit

    fun ldk_node_2e4a_Node_start(`ptr`: Pointer,
                                 _uniffi_out_err: RustCallStatus
    ): Unit

    fun ldk_node_2e4a_Node_stop(`ptr`: Pointer,
                                _uniffi_out_err: RustCallStatus
    ): Unit

    fun ldk_node_2e4a_Node_next_event(`ptr`: Pointer,
                                      _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun ldk_node_2e4a_Node_event_handled(`ptr`: Pointer,
                                         _uniffi_out_err: RustCallStatus
    ): Unit

    fun ldk_node_2e4a_Node_node_id(`ptr`: Pointer,
                                   _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun ldk_node_2e4a_Node_listening_address(`ptr`: Pointer,
                                             _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun ldk_node_2e4a_Node_new_funding_address(`ptr`: Pointer,
                                               _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun ldk_node_2e4a_Node_send_to_onchain_address(`ptr`: Pointer,`address`: RustBuffer.ByValue,`amountMsat`: Long,
                                                   _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun ldk_node_2e4a_Node_send_all_to_onchain_address(`ptr`: Pointer,`address`: RustBuffer.ByValue,
                                                       _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun ldk_node_2e4a_Node_spendable_onchain_balance_sats(`ptr`: Pointer,
                                                          _uniffi_out_err: RustCallStatus
    ): Long

    fun ldk_node_2e4a_Node_total_onchain_balance_sats(`ptr`: Pointer,
                                                      _uniffi_out_err: RustCallStatus
    ): Long

    fun ldk_node_2e4a_Node_connect(`ptr`: Pointer,`nodeId`: RustBuffer.ByValue,`address`: RustBuffer.ByValue,`permanently`: Byte,
                                   _uniffi_out_err: RustCallStatus
    ): Unit

    fun ldk_node_2e4a_Node_disconnect(`ptr`: Pointer,`nodeId`: RustBuffer.ByValue,
                                      _uniffi_out_err: RustCallStatus
    ): Unit

    fun ldk_node_2e4a_Node_connect_open_channel(`ptr`: Pointer,`nodeId`: RustBuffer.ByValue,`address`: RustBuffer.ByValue,`channelAmountSats`: Long,`pushToCounterpartyMsat`: RustBuffer.ByValue,`announceChannel`: Byte,
                                                _uniffi_out_err: RustCallStatus
    ): Unit

    fun ldk_node_2e4a_Node_close_channel(`ptr`: Pointer,`channelId`: RustBuffer.ByValue,`counterpartyNodeId`: RustBuffer.ByValue,
                                         _uniffi_out_err: RustCallStatus
    ): Unit

    fun ldk_node_2e4a_Node_sync_wallets(`ptr`: Pointer,
                                        _uniffi_out_err: RustCallStatus
    ): Unit

    fun ldk_node_2e4a_Node_send_payment(`ptr`: Pointer,`invoice`: RustBuffer.ByValue,
                                        _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun ldk_node_2e4a_Node_send_payment_using_amount(`ptr`: Pointer,`invoice`: RustBuffer.ByValue,`amountMsat`: Long,
                                                     _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun ldk_node_2e4a_Node_send_spontaneous_payment(`ptr`: Pointer,`amountMsat`: Long,`nodeId`: RustBuffer.ByValue,
                                                    _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun ldk_node_2e4a_Node_receive_payment(`ptr`: Pointer,`amountMsat`: Long,`description`: RustBuffer.ByValue,`expirySecs`: Int,
                                           _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun ldk_node_2e4a_Node_receive_variable_amount_payment(`ptr`: Pointer,`description`: RustBuffer.ByValue,`expirySecs`: Int,
                                                           _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun ldk_node_2e4a_Node_payment(`ptr`: Pointer,`paymentHash`: RustBuffer.ByValue,
                                   _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun ldk_node_2e4a_Node_remove_payment(`ptr`: Pointer,`paymentHash`: RustBuffer.ByValue,
                                          _uniffi_out_err: RustCallStatus
    ): Byte

    fun ffi_ldk_node_2e4a_rustbuffer_alloc(`size`: Int,
                                           _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun ffi_ldk_node_2e4a_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,
                                                _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue

    fun ffi_ldk_node_2e4a_rustbuffer_free(`buf`: RustBuffer.ByValue,
                                          _uniffi_out_err: RustCallStatus
    ): Unit

    fun ffi_ldk_node_2e4a_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Int,
                                             _uniffi_out_err: RustCallStatus
    ): RustBuffer.ByValue


}

// Public interface members begin here.


public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

public object FfiConverterULong: FfiConverter<ULong, Long> {
    override fun lift(value: Long): ULong {
        return value.toULong()
    }

    override fun read(buf: ByteBuffer): ULong {
        return lift(buf.getLong())
    }

    override fun lower(value: ULong): Long {
        return value.toLong()
    }

    override fun allocationSize(value: ULong) = 8

    override fun write(value: ULong, buf: ByteBuffer) {
        buf.putLong(value.toLong())
    }
}

public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len)
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteArr = value.toByteArray(Charsets.UTF_8)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteArr.size)
        rbuf.asByteBuffer()!!.put(byteArr)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per unicode codepoint which will always be
    // enough.
    override fun allocationSize(value: String): Int {
        val sizeForLength = 4
        val sizeForString = value.length * 3
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteArr = value.toByteArray(Charsets.UTF_8)
        buf.putInt(byteArr.size)
        buf.put(byteArr)
    }
}


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            args.filterIsInstance<Disposable>()
                .forEach(Disposable::destroy)
        }
    }
}

inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

// The base class for all UniFFI Object types.
//
// This class provides core operations for working with the Rust `Arc<T>` pointer to
// the live Rust struct on the other side of the FFI.
//
// There's some subtlety here, because we have to be careful not to operate on a Rust
// struct after it has been dropped, and because we must expose a public API for freeing
// the Kotlin wrapper object in lieu of reliable finalizers. The core requirements are:
//
//   * Each `FFIObject` instance holds an opaque pointer to the underlying Rust struct.
//     Method calls need to read this pointer from the object's state and pass it in to
//     the Rust FFI.
//
//   * When an `FFIObject` is no longer needed, its pointer should be passed to a
//     special destructor function provided by the Rust FFI, which will drop the
//     underlying Rust struct.
//
//   * Given an `FFIObject` instance, calling code is expected to call the special
//     `destroy` method in order to free it after use, either by calling it explicitly
//     or by using a higher-level helper like the `use` method. Failing to do so will
//     leak the underlying Rust struct.
//
//   * We can't assume that calling code will do the right thing, and must be prepared
//     to handle Kotlin method calls executing concurrently with or even after a call to
//     `destroy`, and to handle multiple (possibly concurrent!) calls to `destroy`.
//
//   * We must never allow Rust code to operate on the underlying Rust struct after
//     the destructor has been called, and must never call the destructor more than once.
//     Doing so may trigger memory unsafety.
//
// If we try to implement this with mutual exclusion on access to the pointer, there is the
// possibility of a race between a method call and a concurrent call to `destroy`:
//
//    * Thread A starts a method call, reads the value of the pointer, but is interrupted
//      before it can pass the pointer over the FFI to Rust.
//    * Thread B calls `destroy` and frees the underlying Rust struct.
//    * Thread A resumes, passing the already-read pointer value to Rust and triggering
//      a use-after-free.
//
// One possible solution would be to use a `ReadWriteLock`, with each method call taking
// a read lock (and thus allowed to run concurrently) and the special `destroy` method
// taking a write lock (and thus blocking on live method calls). However, we aim not to
// generate methods with any hidden blocking semantics, and a `destroy` method that might
// block if called incorrectly seems to meet that bar.
//
// So, we achieve our goals by giving each `FFIObject` an associated `AtomicLong` counter to track
// the number of in-flight method calls, and an `AtomicBoolean` flag to indicate whether `destroy`
// has been called. These are updated according to the following rules:
//
//    * The initial value of the counter is 1, indicating a live object with no in-flight calls.
//      The initial value for the flag is false.
//
//    * At the start of each method call, we atomically check the counter.
//      If it is 0 then the underlying Rust struct has already been destroyed and the call is aborted.
//      If it is nonzero them we atomically increment it by 1 and proceed with the method call.
//
//    * At the end of each method call, we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
//    * When `destroy` is called, we atomically flip the flag from false to true.
//      If the flag was already true we silently fail.
//      Otherwise we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
// Astute readers may observe that this all sounds very similar to the way that Rust's `Arc<T>` works,
// and indeed it is, with the addition of a flag to guard against multiple calls to `destroy`.
//
// The overall effect is that the underlying Rust struct is destroyed only when `destroy` has been
// called *and* all in-flight method calls have completed, avoiding violating any of the expectations
// of the underlying Rust code.
//
// In the future we may be able to replace some of this with automatic finalization logic, such as using
// the new "Cleaner" functionaility in Java 9. The above scheme has been designed to work even if `destroy` is
// invoked by garbage-collection machinery rather than by calling code (which by the way, it's apparently also
// possible for the JVM to finalize an object while there is an in-flight call to one of its methods [1],
// so there would still be some complexity here).
//
// Sigh...all of this for want of a robust finalization mechanism.
//
// [1] https://stackoverflow.com/questions/24376768/can-java-finalize-an-object-when-it-is-still-in-scope/24380219
//
abstract class FFIObject(
    protected val pointer: Pointer
): Disposable, AutoCloseable {

    private val wasDestroyed = AtomicBoolean(false)
    private val callCounter = AtomicLong(1)

    open protected fun freeRustArcPtr() {
        // To be overridden in subclasses.
    }

    override fun destroy() {
        // Only allow a single call to this method.
        // TODO: maybe we should log a warning if called more than once?
        if (this.wasDestroyed.compareAndSet(false, true)) {
            // This decrement always matches the initial count of 1 given at creation time.
            if (this.callCounter.decrementAndGet() == 0L) {
                this.freeRustArcPtr()
            }
        }
    }

    @Synchronized
    override fun close() {
        this.destroy()
    }

    internal inline fun <R> callWithPointer(block: (ptr: Pointer) -> R): R {
        // Check and increment the call counter, to keep the object alive.
        // This needs a compare-and-set retry loop in case of concurrent updates.
        do {
            val c = this.callCounter.get()
            if (c == 0L) {
                throw IllegalStateException("${this.javaClass.simpleName} object has already been destroyed")
            }
            if (c == Long.MAX_VALUE) {
                throw IllegalStateException("${this.javaClass.simpleName} call counter would overflow")
            }
        } while (! this.callCounter.compareAndSet(c, c + 1L))
        // Now we can safely do the method call without the pointer being freed concurrently.
        try {
            return block(this.pointer)
        } finally {
            // This decrement always matches the increment we performed above.
            if (this.callCounter.decrementAndGet() == 0L) {
                this.freeRustArcPtr()
            }
        }
    }
}

public interface BuilderInterface {

    fun `build`(): Node

}

class Builder(
    pointer: Pointer
) : FFIObject(pointer), BuilderInterface {
    constructor() :
            this(
                rustCall() { _status ->
                    _UniFFILib.INSTANCE.ldk_node_2e4a_Builder_new( _status)
                })

    /**
     * Disconnect the object from the underlying Rust object.
     *
     * It can be called more than once, but once called, interacting with the object
     * causes an `IllegalStateException`.
     *
     * Clients **must** call this method once done with the object, or cause a memory leak.
     */
    override protected fun freeRustArcPtr() {
        rustCall() { status ->
            _UniFFILib.INSTANCE.ffi_ldk_node_2e4a_Builder_object_free(this.pointer, status)
        }
    }

    override fun `build`(): Node =
        callWithPointer {
            rustCall() { _status ->
                _UniFFILib.INSTANCE.ldk_node_2e4a_Builder_build(it,  _status)
            }
        }.let {
            FfiConverterTypeNode.lift(it)
        }


    companion object {
        fun `fromConfig`(`config`: Config): Builder =
            Builder(
                rustCall() { _status ->
                    _UniFFILib.INSTANCE.ldk_node_2e4a_Builder_from_config(FfiConverterTypeConfig.lower(`config`), _status)
                })

    }

}

public object FfiConverterTypeBuilder: FfiConverter<Builder, Pointer> {
    override fun lower(value: Builder): Pointer = value.callWithPointer { it }

    override fun lift(value: Pointer): Builder {
        return Builder(value)
    }

    override fun read(buf: ByteBuffer): Builder {
        // The Rust code always writes pointers as 8 bytes, and will
        // fail to compile if they don't fit.
        return lift(Pointer(buf.getLong()))
    }

    override fun allocationSize(value: Builder) = 8

    override fun write(value: Builder, buf: ByteBuffer) {
        // The Rust code always expects pointers written as 8 bytes,
        // and will fail to compile if they don't fit.
        buf.putLong(Pointer.nativeValue(lower(value)))
    }
}




public interface NodeInterface {

    @Throws(NodeException::class)
    fun `start`()

    @Throws(NodeException::class)
    fun `stop`()

    fun `nextEvent`(): Event

    fun `eventHandled`()

    fun `nodeId`(): PublicKey

    fun `listeningAddress`(): SocketAddr?

    @Throws(NodeException::class)
    fun `newFundingAddress`(): Address

    @Throws(NodeException::class)
    fun `sendToOnchainAddress`(`address`: Address, `amountMsat`: ULong): Txid

    @Throws(NodeException::class)
    fun `sendAllToOnchainAddress`(`address`: Address): Txid

    @Throws(NodeException::class)
    fun `spendableOnchainBalanceSats`(): ULong

    @Throws(NodeException::class)
    fun `totalOnchainBalanceSats`(): ULong

    @Throws(NodeException::class)
    fun `connect`(`nodeId`: PublicKey, `address`: SocketAddr, `permanently`: Boolean)

    @Throws(NodeException::class)
    fun `disconnect`(`nodeId`: PublicKey)

    @Throws(NodeException::class)
    fun `connectOpenChannel`(`nodeId`: PublicKey, `address`: SocketAddr, `channelAmountSats`: ULong, `pushToCounterpartyMsat`: ULong?, `announceChannel`: Boolean)

    @Throws(NodeException::class)
    fun `closeChannel`(`channelId`: ChannelId, `counterpartyNodeId`: PublicKey)

    @Throws(NodeException::class)
    fun `syncWallets`()

    @Throws(NodeException::class)
    fun `sendPayment`(`invoice`: Invoice): PaymentHash

    @Throws(NodeException::class)
    fun `sendPaymentUsingAmount`(`invoice`: Invoice, `amountMsat`: ULong): PaymentHash

    @Throws(NodeException::class)
    fun `sendSpontaneousPayment`(`amountMsat`: ULong, `nodeId`: PublicKey): PaymentHash

    @Throws(NodeException::class)
    fun `receivePayment`(`amountMsat`: ULong, `description`: String, `expirySecs`: UInt): Invoice

    @Throws(NodeException::class)
    fun `receiveVariableAmountPayment`(`description`: String, `expirySecs`: UInt): Invoice

    fun `payment`(`paymentHash`: PaymentHash): PaymentDetails?

    @Throws(NodeException::class)
    fun `removePayment`(`paymentHash`: PaymentHash): Boolean

}

class Node(
    pointer: Pointer
) : FFIObject(pointer), NodeInterface {

    /**
     * Disconnect the object from the underlying Rust object.
     *
     * It can be called more than once, but once called, interacting with the object
     * causes an `IllegalStateException`.
     *
     * Clients **must** call this method once done with the object, or cause a memory leak.
     */
    override protected fun freeRustArcPtr() {
        rustCall() { status ->
            _UniFFILib.INSTANCE.ffi_ldk_node_2e4a_Node_object_free(this.pointer, status)
        }
    }


    @Throws(NodeException::class)override fun `start`() =
        callWithPointer {
            rustCallWithError(NodeException) { _status ->
                _UniFFILib.INSTANCE.ldk_node_2e4a_Node_start(it,  _status)
            }
        }


    @Throws(NodeException::class)override fun `stop`() =
        callWithPointer {
            rustCallWithError(NodeException) { _status ->
                _UniFFILib.INSTANCE.ldk_node_2e4a_Node_stop(it,  _status)
            }
        }

    override fun `nextEvent`(): Event =
        callWithPointer {
            rustCall() { _status ->
                _UniFFILib.INSTANCE.ldk_node_2e4a_Node_next_event(it,  _status)
            }
        }.let {
            FfiConverterTypeEvent.lift(it)
        }
    override fun `eventHandled`() =
        callWithPointer {
            rustCall() { _status ->
                _UniFFILib.INSTANCE.ldk_node_2e4a_Node_event_handled(it,  _status)
            }
        }

    override fun `nodeId`(): PublicKey =
        callWithPointer {
            rustCall() { _status ->
                _UniFFILib.INSTANCE.ldk_node_2e4a_Node_node_id(it,  _status)
            }
        }.let {
            FfiConverterTypePublicKey.lift(it)
        }
    override fun `listeningAddress`(): SocketAddr? =
        callWithPointer {
            rustCall() { _status ->
                _UniFFILib.INSTANCE.ldk_node_2e4a_Node_listening_address(it,  _status)
            }
        }.let {
            FfiConverterOptionalTypeSocketAddr.lift(it)
        }

    @Throws(NodeException::class)override fun `newFundingAddress`(): Address =
        callWithPointer {
            rustCallWithError(NodeException) { _status ->
                _UniFFILib.INSTANCE.ldk_node_2e4a_Node_new_funding_address(it,  _status)
            }
        }.let {
            FfiConverterTypeAddress.lift(it)
        }

    @Throws(NodeException::class)override fun `sendToOnchainAddress`(`address`: Address, `amountMsat`: ULong): Txid =
        callWithPointer {
            rustCallWithError(NodeException) { _status ->
                _UniFFILib.INSTANCE.ldk_node_2e4a_Node_send_to_onchain_address(it, FfiConverterTypeAddress.lower(`address`), FfiConverterULong.lower(`amountMsat`),  _status)
            }
        }.let {
            FfiConverterTypeTxid.lift(it)
        }

    @Throws(NodeException::class)override fun `sendAllToOnchainAddress`(`address`: Address): Txid =
        callWithPointer {
            rustCallWithError(NodeException) { _status ->
                _UniFFILib.INSTANCE.ldk_node_2e4a_Node_send_all_to_onchain_address(it, FfiConverterTypeAddress.lower(`address`),  _status)
            }
        }.let {
            FfiConverterTypeTxid.lift(it)
        }

    @Throws(NodeException::class)override fun `spendableOnchainBalanceSats`(): ULong =
        callWithPointer {
            rustCallWithError(NodeException) { _status ->
                _UniFFILib.INSTANCE.ldk_node_2e4a_Node_spendable_onchain_balance_sats(it,  _status)
            }
        }.let {
            FfiConverterULong.lift(it)
        }

    @Throws(NodeException::class)override fun `totalOnchainBalanceSats`(): ULong =
        callWithPointer {
            rustCallWithError(NodeException) { _status ->
                _UniFFILib.INSTANCE.ldk_node_2e4a_Node_total_onchain_balance_sats(it,  _status)
            }
        }.let {
            FfiConverterULong.lift(it)
        }

    @Throws(NodeException::class)override fun `connect`(`nodeId`: PublicKey, `address`: SocketAddr, `permanently`: Boolean) =
        callWithPointer {
            rustCallWithError(NodeException) { _status ->
                _UniFFILib.INSTANCE.ldk_node_2e4a_Node_connect(it, FfiConverterTypePublicKey.lower(`nodeId`), FfiConverterTypeSocketAddr.lower(`address`), FfiConverterBoolean.lower(`permanently`),  _status)
            }
        }


    @Throws(NodeException::class)override fun `disconnect`(`nodeId`: PublicKey) =
        callWithPointer {
            rustCallWithError(NodeException) { _status ->
                _UniFFILib.INSTANCE.ldk_node_2e4a_Node_disconnect(it, FfiConverterTypePublicKey.lower(`nodeId`),  _status)
            }
        }


    @Throws(NodeException::class)override fun `connectOpenChannel`(`nodeId`: PublicKey, `address`: SocketAddr, `channelAmountSats`: ULong, `pushToCounterpartyMsat`: ULong?, `announceChannel`: Boolean) =
        callWithPointer {
            rustCallWithError(NodeException) { _status ->
                _UniFFILib.INSTANCE.ldk_node_2e4a_Node_connect_open_channel(it, FfiConverterTypePublicKey.lower(`nodeId`), FfiConverterTypeSocketAddr.lower(`address`), FfiConverterULong.lower(`channelAmountSats`), FfiConverterOptionalULong.lower(`pushToCounterpartyMsat`), FfiConverterBoolean.lower(`announceChannel`),  _status)
            }
        }


    @Throws(NodeException::class)override fun `closeChannel`(`channelId`: ChannelId, `counterpartyNodeId`: PublicKey) =
        callWithPointer {
            rustCallWithError(NodeException) { _status ->
                _UniFFILib.INSTANCE.ldk_node_2e4a_Node_close_channel(it, FfiConverterTypeChannelId.lower(`channelId`), FfiConverterTypePublicKey.lower(`counterpartyNodeId`),  _status)
            }
        }


    @Throws(NodeException::class)override fun `syncWallets`() =
        callWithPointer {
            rustCallWithError(NodeException) { _status ->
                _UniFFILib.INSTANCE.ldk_node_2e4a_Node_sync_wallets(it,  _status)
            }
        }


    @Throws(NodeException::class)override fun `sendPayment`(`invoice`: Invoice): PaymentHash =
        callWithPointer {
            rustCallWithError(NodeException) { _status ->
                _UniFFILib.INSTANCE.ldk_node_2e4a_Node_send_payment(it, FfiConverterTypeInvoice.lower(`invoice`),  _status)
            }
        }.let {
            FfiConverterTypePaymentHash.lift(it)
        }

    @Throws(NodeException::class)override fun `sendPaymentUsingAmount`(`invoice`: Invoice, `amountMsat`: ULong): PaymentHash =
        callWithPointer {
            rustCallWithError(NodeException) { _status ->
                _UniFFILib.INSTANCE.ldk_node_2e4a_Node_send_payment_using_amount(it, FfiConverterTypeInvoice.lower(`invoice`), FfiConverterULong.lower(`amountMsat`),  _status)
            }
        }.let {
            FfiConverterTypePaymentHash.lift(it)
        }

    @Throws(NodeException::class)override fun `sendSpontaneousPayment`(`amountMsat`: ULong, `nodeId`: PublicKey): PaymentHash =
        callWithPointer {
            rustCallWithError(NodeException) { _status ->
                _UniFFILib.INSTANCE.ldk_node_2e4a_Node_send_spontaneous_payment(it, FfiConverterULong.lower(`amountMsat`), FfiConverterTypePublicKey.lower(`nodeId`),  _status)
            }
        }.let {
            FfiConverterTypePaymentHash.lift(it)
        }

    @Throws(NodeException::class)override fun `receivePayment`(`amountMsat`: ULong, `description`: String, `expirySecs`: UInt): Invoice =
        callWithPointer {
            rustCallWithError(NodeException) { _status ->
                _UniFFILib.INSTANCE.ldk_node_2e4a_Node_receive_payment(it, FfiConverterULong.lower(`amountMsat`), FfiConverterString.lower(`description`), FfiConverterUInt.lower(`expirySecs`),  _status)
            }
        }.let {
            FfiConverterTypeInvoice.lift(it)
        }

    @Throws(NodeException::class)override fun `receiveVariableAmountPayment`(`description`: String, `expirySecs`: UInt): Invoice =
        callWithPointer {
            rustCallWithError(NodeException) { _status ->
                _UniFFILib.INSTANCE.ldk_node_2e4a_Node_receive_variable_amount_payment(it, FfiConverterString.lower(`description`), FfiConverterUInt.lower(`expirySecs`),  _status)
            }
        }.let {
            FfiConverterTypeInvoice.lift(it)
        }
    override fun `payment`(`paymentHash`: PaymentHash): PaymentDetails? =
        callWithPointer {
            rustCall() { _status ->
                _UniFFILib.INSTANCE.ldk_node_2e4a_Node_payment(it, FfiConverterTypePaymentHash.lower(`paymentHash`),  _status)
            }
        }.let {
            FfiConverterOptionalTypePaymentDetails.lift(it)
        }

    @Throws(NodeException::class)override fun `removePayment`(`paymentHash`: PaymentHash): Boolean =
        callWithPointer {
            rustCallWithError(NodeException) { _status ->
                _UniFFILib.INSTANCE.ldk_node_2e4a_Node_remove_payment(it, FfiConverterTypePaymentHash.lower(`paymentHash`),  _status)
            }
        }.let {
            FfiConverterBoolean.lift(it)
        }



}

public object FfiConverterTypeNode: FfiConverter<Node, Pointer> {
    override fun lower(value: Node): Pointer = value.callWithPointer { it }

    override fun lift(value: Pointer): Node {
        return Node(value)
    }

    override fun read(buf: ByteBuffer): Node {
        // The Rust code always writes pointers as 8 bytes, and will
        // fail to compile if they don't fit.
        return lift(Pointer(buf.getLong()))
    }

    override fun allocationSize(value: Node) = 8

    override fun write(value: Node, buf: ByteBuffer) {
        // The Rust code always expects pointers written as 8 bytes,
        // and will fail to compile if they don't fit.
        buf.putLong(Pointer.nativeValue(lower(value)))
    }
}




data class Config (
    var `storageDirPath`: String,
    var `esploraServerUrl`: String,
    var `network`: Network,
    var `listeningAddress`: SocketAddr?,
    var `defaultCltvExpiryDelta`: UInt
) {

}

public object FfiConverterTypeConfig: FfiConverterRustBuffer<Config> {
    override fun read(buf: ByteBuffer): Config {
        return Config(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterTypeNetwork.read(buf),
            FfiConverterOptionalTypeSocketAddr.read(buf),
            FfiConverterUInt.read(buf),
        )
    }

    override fun allocationSize(value: Config) = (
            FfiConverterString.allocationSize(value.`storageDirPath`) +
                    FfiConverterString.allocationSize(value.`esploraServerUrl`) +
                    FfiConverterTypeNetwork.allocationSize(value.`network`) +
                    FfiConverterOptionalTypeSocketAddr.allocationSize(value.`listeningAddress`) +
                    FfiConverterUInt.allocationSize(value.`defaultCltvExpiryDelta`)
            )

    override fun write(value: Config, buf: ByteBuffer) {
        FfiConverterString.write(value.`storageDirPath`, buf)
        FfiConverterString.write(value.`esploraServerUrl`, buf)
        FfiConverterTypeNetwork.write(value.`network`, buf)
        FfiConverterOptionalTypeSocketAddr.write(value.`listeningAddress`, buf)
        FfiConverterUInt.write(value.`defaultCltvExpiryDelta`, buf)
    }
}




data class OutPoint (
    var `txid`: Txid,
    var `vout`: UInt
) {

}

public object FfiConverterTypeOutPoint: FfiConverterRustBuffer<OutPoint> {
    override fun read(buf: ByteBuffer): OutPoint {
        return OutPoint(
            FfiConverterTypeTxid.read(buf),
            FfiConverterUInt.read(buf),
        )
    }

    override fun allocationSize(value: OutPoint) = (
            FfiConverterTypeTxid.allocationSize(value.`txid`) +
                    FfiConverterUInt.allocationSize(value.`vout`)
            )

    override fun write(value: OutPoint, buf: ByteBuffer) {
        FfiConverterTypeTxid.write(value.`txid`, buf)
        FfiConverterUInt.write(value.`vout`, buf)
    }
}




data class PaymentDetails (
    var `hash`: PaymentHash,
    var `preimage`: PaymentPreimage?,
    var `secret`: PaymentSecret?,
    var `amountMsat`: ULong?,
    var `direction`: PaymentDirection,
    var `status`: PaymentStatus
) {

}

public object FfiConverterTypePaymentDetails: FfiConverterRustBuffer<PaymentDetails> {
    override fun read(buf: ByteBuffer): PaymentDetails {
        return PaymentDetails(
            FfiConverterTypePaymentHash.read(buf),
            FfiConverterOptionalTypePaymentPreimage.read(buf),
            FfiConverterOptionalTypePaymentSecret.read(buf),
            FfiConverterOptionalULong.read(buf),
            FfiConverterTypePaymentDirection.read(buf),
            FfiConverterTypePaymentStatus.read(buf),
        )
    }

    override fun allocationSize(value: PaymentDetails) = (
            FfiConverterTypePaymentHash.allocationSize(value.`hash`) +
                    FfiConverterOptionalTypePaymentPreimage.allocationSize(value.`preimage`) +
                    FfiConverterOptionalTypePaymentSecret.allocationSize(value.`secret`) +
                    FfiConverterOptionalULong.allocationSize(value.`amountMsat`) +
                    FfiConverterTypePaymentDirection.allocationSize(value.`direction`) +
                    FfiConverterTypePaymentStatus.allocationSize(value.`status`)
            )

    override fun write(value: PaymentDetails, buf: ByteBuffer) {
        FfiConverterTypePaymentHash.write(value.`hash`, buf)
        FfiConverterOptionalTypePaymentPreimage.write(value.`preimage`, buf)
        FfiConverterOptionalTypePaymentSecret.write(value.`secret`, buf)
        FfiConverterOptionalULong.write(value.`amountMsat`, buf)
        FfiConverterTypePaymentDirection.write(value.`direction`, buf)
        FfiConverterTypePaymentStatus.write(value.`status`, buf)
    }
}




sealed class Event {
    data class PaymentSuccessful(
        val `paymentHash`: PaymentHash
    ) : Event()
    data class PaymentFailed(
        val `paymentHash`: PaymentHash
    ) : Event()
    data class PaymentReceived(
        val `paymentHash`: PaymentHash,
        val `amountMsat`: ULong
    ) : Event()
    data class ChannelPending(
        val `channelId`: ChannelId,
        val `userChannelId`: UserChannelId,
        val `formerTemporaryChannelId`: ChannelId,
        val `counterpartyNodeId`: PublicKey,
        val `fundingTxo`: OutPoint
    ) : Event()
    data class ChannelReady(
        val `channelId`: ChannelId,
        val `userChannelId`: UserChannelId
    ) : Event()
    data class ChannelClosed(
        val `channelId`: ChannelId,
        val `userChannelId`: UserChannelId
    ) : Event()



}

public object FfiConverterTypeEvent : FfiConverterRustBuffer<Event>{
    override fun read(buf: ByteBuffer): Event {
        return when(buf.getInt()) {
            1 -> Event.PaymentSuccessful(
                FfiConverterTypePaymentHash.read(buf),
            )
            2 -> Event.PaymentFailed(
                FfiConverterTypePaymentHash.read(buf),
            )
            3 -> Event.PaymentReceived(
                FfiConverterTypePaymentHash.read(buf),
                FfiConverterULong.read(buf),
            )
            4 -> Event.ChannelPending(
                FfiConverterTypeChannelId.read(buf),
                FfiConverterTypeUserChannelId.read(buf),
                FfiConverterTypeChannelId.read(buf),
                FfiConverterTypePublicKey.read(buf),
                FfiConverterTypeOutPoint.read(buf),
            )
            5 -> Event.ChannelReady(
                FfiConverterTypeChannelId.read(buf),
                FfiConverterTypeUserChannelId.read(buf),
            )
            6 -> Event.ChannelClosed(
                FfiConverterTypeChannelId.read(buf),
                FfiConverterTypeUserChannelId.read(buf),
            )
            else -> throw RuntimeException("invalid enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: Event) = when(value) {
        is Event.PaymentSuccessful -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                    4
                            + FfiConverterTypePaymentHash.allocationSize(value.`paymentHash`)
                    )
        }
        is Event.PaymentFailed -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                    4
                            + FfiConverterTypePaymentHash.allocationSize(value.`paymentHash`)
                    )
        }
        is Event.PaymentReceived -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                    4
                            + FfiConverterTypePaymentHash.allocationSize(value.`paymentHash`)
                            + FfiConverterULong.allocationSize(value.`amountMsat`)
                    )
        }
        is Event.ChannelPending -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                    4
                            + FfiConverterTypeChannelId.allocationSize(value.`channelId`)
                            + FfiConverterTypeUserChannelId.allocationSize(value.`userChannelId`)
                            + FfiConverterTypeChannelId.allocationSize(value.`formerTemporaryChannelId`)
                            + FfiConverterTypePublicKey.allocationSize(value.`counterpartyNodeId`)
                            + FfiConverterTypeOutPoint.allocationSize(value.`fundingTxo`)
                    )
        }
        is Event.ChannelReady -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                    4
                            + FfiConverterTypeChannelId.allocationSize(value.`channelId`)
                            + FfiConverterTypeUserChannelId.allocationSize(value.`userChannelId`)
                    )
        }
        is Event.ChannelClosed -> {
            // Add the size for the Int that specifies the variant plus the size needed for all fields
            (
                    4
                            + FfiConverterTypeChannelId.allocationSize(value.`channelId`)
                            + FfiConverterTypeUserChannelId.allocationSize(value.`userChannelId`)
                    )
        }
    }

    override fun write(value: Event, buf: ByteBuffer) {
        when(value) {
            is Event.PaymentSuccessful -> {
                buf.putInt(1)
                FfiConverterTypePaymentHash.write(value.`paymentHash`, buf)
                Unit
            }
            is Event.PaymentFailed -> {
                buf.putInt(2)
                FfiConverterTypePaymentHash.write(value.`paymentHash`, buf)
                Unit
            }
            is Event.PaymentReceived -> {
                buf.putInt(3)
                FfiConverterTypePaymentHash.write(value.`paymentHash`, buf)
                FfiConverterULong.write(value.`amountMsat`, buf)
                Unit
            }
            is Event.ChannelPending -> {
                buf.putInt(4)
                FfiConverterTypeChannelId.write(value.`channelId`, buf)
                FfiConverterTypeUserChannelId.write(value.`userChannelId`, buf)
                FfiConverterTypeChannelId.write(value.`formerTemporaryChannelId`, buf)
                FfiConverterTypePublicKey.write(value.`counterpartyNodeId`, buf)
                FfiConverterTypeOutPoint.write(value.`fundingTxo`, buf)
                Unit
            }
            is Event.ChannelReady -> {
                buf.putInt(5)
                FfiConverterTypeChannelId.write(value.`channelId`, buf)
                FfiConverterTypeUserChannelId.write(value.`userChannelId`, buf)
                Unit
            }
            is Event.ChannelClosed -> {
                buf.putInt(6)
                FfiConverterTypeChannelId.write(value.`channelId`, buf)
                FfiConverterTypeUserChannelId.write(value.`userChannelId`, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }
}






enum class PaymentDirection {
    INBOUND,OUTBOUND;
}

public object FfiConverterTypePaymentDirection: FfiConverterRustBuffer<PaymentDirection> {
    override fun read(buf: ByteBuffer) = try {
        PaymentDirection.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: PaymentDirection) = 4

    override fun write(value: PaymentDirection, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class PaymentStatus {
    PENDING,SUCCEEDED,FAILED;
}

public object FfiConverterTypePaymentStatus: FfiConverterRustBuffer<PaymentStatus> {
    override fun read(buf: ByteBuffer) = try {
        PaymentStatus.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: PaymentStatus) = 4

    override fun write(value: PaymentStatus, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}







sealed class NodeException(message: String): Exception(message) {
    // Each variant is a nested class
    // Flat enums carries a string error message, so no special implementation is necessary.
    class AlreadyRunning(message: String) : NodeException(message)
    class NotRunning(message: String) : NodeException(message)
    class OnchainTxCreationFailed(message: String) : NodeException(message)
    class ConnectionFailed(message: String) : NodeException(message)
    class InvoiceCreationFailed(message: String) : NodeException(message)
    class PaymentFailed(message: String) : NodeException(message)
    class PeerInfoParseFailed(message: String) : NodeException(message)
    class ChannelCreationFailed(message: String) : NodeException(message)
    class ChannelClosingFailed(message: String) : NodeException(message)
    class PersistenceFailed(message: String) : NodeException(message)
    class WalletOperationFailed(message: String) : NodeException(message)
    class WalletSigningFailed(message: String) : NodeException(message)
    class TxSyncFailed(message: String) : NodeException(message)
    class InvalidAddress(message: String) : NodeException(message)
    class InvalidPublicKey(message: String) : NodeException(message)
    class InvalidPaymentHash(message: String) : NodeException(message)
    class InvalidPaymentPreimage(message: String) : NodeException(message)
    class InvalidPaymentSecret(message: String) : NodeException(message)
    class InvalidAmount(message: String) : NodeException(message)
    class InvalidInvoice(message: String) : NodeException(message)
    class InvalidChannelId(message: String) : NodeException(message)
    class InvalidNetwork(message: String) : NodeException(message)
    class NonUniquePaymentHash(message: String) : NodeException(message)
    class InsufficientFunds(message: String) : NodeException(message)


    companion object ErrorHandler : CallStatusErrorHandler<NodeException> {
        override fun lift(error_buf: RustBuffer.ByValue): NodeException = FfiConverterTypeNodeError.lift(error_buf)
    }
}

public object FfiConverterTypeNodeError : FfiConverterRustBuffer<NodeException> {
    override fun read(buf: ByteBuffer): NodeException {

        return when(buf.getInt()) {
            1 -> NodeException.AlreadyRunning(FfiConverterString.read(buf))
            2 -> NodeException.NotRunning(FfiConverterString.read(buf))
            3 -> NodeException.OnchainTxCreationFailed(FfiConverterString.read(buf))
            4 -> NodeException.ConnectionFailed(FfiConverterString.read(buf))
            5 -> NodeException.InvoiceCreationFailed(FfiConverterString.read(buf))
            6 -> NodeException.PaymentFailed(FfiConverterString.read(buf))
            7 -> NodeException.PeerInfoParseFailed(FfiConverterString.read(buf))
            8 -> NodeException.ChannelCreationFailed(FfiConverterString.read(buf))
            9 -> NodeException.ChannelClosingFailed(FfiConverterString.read(buf))
            10 -> NodeException.PersistenceFailed(FfiConverterString.read(buf))
            11 -> NodeException.WalletOperationFailed(FfiConverterString.read(buf))
            12 -> NodeException.WalletSigningFailed(FfiConverterString.read(buf))
            13 -> NodeException.TxSyncFailed(FfiConverterString.read(buf))
            14 -> NodeException.InvalidAddress(FfiConverterString.read(buf))
            15 -> NodeException.InvalidPublicKey(FfiConverterString.read(buf))
            16 -> NodeException.InvalidPaymentHash(FfiConverterString.read(buf))
            17 -> NodeException.InvalidPaymentPreimage(FfiConverterString.read(buf))
            18 -> NodeException.InvalidPaymentSecret(FfiConverterString.read(buf))
            19 -> NodeException.InvalidAmount(FfiConverterString.read(buf))
            20 -> NodeException.InvalidInvoice(FfiConverterString.read(buf))
            21 -> NodeException.InvalidChannelId(FfiConverterString.read(buf))
            22 -> NodeException.InvalidNetwork(FfiConverterString.read(buf))
            23 -> NodeException.NonUniquePaymentHash(FfiConverterString.read(buf))
            24 -> NodeException.InsufficientFunds(FfiConverterString.read(buf))
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }

    }

    override fun allocationSize(value: NodeException): Int {
        return 4
    }

    override fun write(value: NodeException, buf: ByteBuffer) {
        when(value) {
            is NodeException.AlreadyRunning -> {
                buf.putInt(1)
                Unit
            }
            is NodeException.NotRunning -> {
                buf.putInt(2)
                Unit
            }
            is NodeException.OnchainTxCreationFailed -> {
                buf.putInt(3)
                Unit
            }
            is NodeException.ConnectionFailed -> {
                buf.putInt(4)
                Unit
            }
            is NodeException.InvoiceCreationFailed -> {
                buf.putInt(5)
                Unit
            }
            is NodeException.PaymentFailed -> {
                buf.putInt(6)
                Unit
            }
            is NodeException.PeerInfoParseFailed -> {
                buf.putInt(7)
                Unit
            }
            is NodeException.ChannelCreationFailed -> {
                buf.putInt(8)
                Unit
            }
            is NodeException.ChannelClosingFailed -> {
                buf.putInt(9)
                Unit
            }
            is NodeException.PersistenceFailed -> {
                buf.putInt(10)
                Unit
            }
            is NodeException.WalletOperationFailed -> {
                buf.putInt(11)
                Unit
            }
            is NodeException.WalletSigningFailed -> {
                buf.putInt(12)
                Unit
            }
            is NodeException.TxSyncFailed -> {
                buf.putInt(13)
                Unit
            }
            is NodeException.InvalidAddress -> {
                buf.putInt(14)
                Unit
            }
            is NodeException.InvalidPublicKey -> {
                buf.putInt(15)
                Unit
            }
            is NodeException.InvalidPaymentHash -> {
                buf.putInt(16)
                Unit
            }
            is NodeException.InvalidPaymentPreimage -> {
                buf.putInt(17)
                Unit
            }
            is NodeException.InvalidPaymentSecret -> {
                buf.putInt(18)
                Unit
            }
            is NodeException.InvalidAmount -> {
                buf.putInt(19)
                Unit
            }
            is NodeException.InvalidInvoice -> {
                buf.putInt(20)
                Unit
            }
            is NodeException.InvalidChannelId -> {
                buf.putInt(21)
                Unit
            }
            is NodeException.InvalidNetwork -> {
                buf.putInt(22)
                Unit
            }
            is NodeException.NonUniquePaymentHash -> {
                buf.putInt(23)
                Unit
            }
            is NodeException.InsufficientFunds -> {
                buf.putInt(24)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}




public object FfiConverterOptionalULong: FfiConverterRustBuffer<ULong?> {
    override fun read(buf: ByteBuffer): ULong? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterULong.read(buf)
    }

    override fun allocationSize(value: ULong?): Int {
        if (value == null) {
            return 1
        } else {
            return 1 + FfiConverterULong.allocationSize(value)
        }
    }

    override fun write(value: ULong?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterULong.write(value, buf)
        }
    }
}




public object FfiConverterOptionalTypePaymentDetails: FfiConverterRustBuffer<PaymentDetails?> {
    override fun read(buf: ByteBuffer): PaymentDetails? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypePaymentDetails.read(buf)
    }

    override fun allocationSize(value: PaymentDetails?): Int {
        if (value == null) {
            return 1
        } else {
            return 1 + FfiConverterTypePaymentDetails.allocationSize(value)
        }
    }

    override fun write(value: PaymentDetails?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypePaymentDetails.write(value, buf)
        }
    }
}




public object FfiConverterOptionalTypePaymentPreimage: FfiConverterRustBuffer<PaymentPreimage?> {
    override fun read(buf: ByteBuffer): PaymentPreimage? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypePaymentPreimage.read(buf)
    }

    override fun allocationSize(value: PaymentPreimage?): Int {
        if (value == null) {
            return 1
        } else {
            return 1 + FfiConverterTypePaymentPreimage.allocationSize(value)
        }
    }

    override fun write(value: PaymentPreimage?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypePaymentPreimage.write(value, buf)
        }
    }
}




public object FfiConverterOptionalTypePaymentSecret: FfiConverterRustBuffer<PaymentSecret?> {
    override fun read(buf: ByteBuffer): PaymentSecret? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypePaymentSecret.read(buf)
    }

    override fun allocationSize(value: PaymentSecret?): Int {
        if (value == null) {
            return 1
        } else {
            return 1 + FfiConverterTypePaymentSecret.allocationSize(value)
        }
    }

    override fun write(value: PaymentSecret?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypePaymentSecret.write(value, buf)
        }
    }
}




public object FfiConverterOptionalTypeSocketAddr: FfiConverterRustBuffer<SocketAddr?> {
    override fun read(buf: ByteBuffer): SocketAddr? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeSocketAddr.read(buf)
    }

    override fun allocationSize(value: SocketAddr?): Int {
        if (value == null) {
            return 1
        } else {
            return 1 + FfiConverterTypeSocketAddr.allocationSize(value)
        }
    }

    override fun write(value: SocketAddr?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeSocketAddr.write(value, buf)
        }
    }
}



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 * It's also what we have an external type that references a custom type.
 */
public typealias Address = String
public typealias FfiConverterTypeAddress = FfiConverterString



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 * It's also what we have an external type that references a custom type.
 */
public typealias ChannelId = String
public typealias FfiConverterTypeChannelId = FfiConverterString



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 * It's also what we have an external type that references a custom type.
 */
public typealias Invoice = String
public typealias FfiConverterTypeInvoice = FfiConverterString



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 * It's also what we have an external type that references a custom type.
 */
public typealias Network = String
public typealias FfiConverterTypeNetwork = FfiConverterString



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 * It's also what we have an external type that references a custom type.
 */
public typealias PaymentHash = String
public typealias FfiConverterTypePaymentHash = FfiConverterString



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 * It's also what we have an external type that references a custom type.
 */
public typealias PaymentPreimage = String
public typealias FfiConverterTypePaymentPreimage = FfiConverterString



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 * It's also what we have an external type that references a custom type.
 */
public typealias PaymentSecret = String
public typealias FfiConverterTypePaymentSecret = FfiConverterString



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 * It's also what we have an external type that references a custom type.
 */
public typealias PublicKey = String
public typealias FfiConverterTypePublicKey = FfiConverterString



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 * It's also what we have an external type that references a custom type.
 */
public typealias SocketAddr = String
public typealias FfiConverterTypeSocketAddr = FfiConverterString



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 * It's also what we have an external type that references a custom type.
 */
public typealias Txid = String
public typealias FfiConverterTypeTxid = FfiConverterString



/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 * It's also what we have an external type that references a custom type.
 */
public typealias UserChannelId = String
public typealias FfiConverterTypeUserChannelId = FfiConverterString


